- name: Installing script dependencies (pacman)
  pacman:
    name: libboost-dev
    state: present
  become: true
  when: package_manager == "pacman"

- name: Installing script dependencies (apt)
  apt:
    name: libboost-dev
    state: present
  become: true
  when: package_manager == "apt"

- name: Clone terminal-scripts repo
  git:
    repo: "https://github.com/Irubataru/terminal-scripts.git"
    dest: "{{ role_path }}/terminal-scripts"

- name: Initialise terminal-scripts path file
  template: 
    src: "path.zsh.j2"
    dest: "{{ role_path }}/_path.zsh"

- name: Clone terminal-programs repo
  git:
    repo: "https://github.com/Irubataru/terminal-programs.git"
    dest: "{{ role_path }}/terminal-programs"
  register: terminal_programs_clone

- name: Build terminal-programs
  make:
    chdir: "{{ role_path }}/terminal-programs"
  when:
    - not terminal_programs_clone.failed
    - terminal_programs_clone.changed
  register: terminal_programs_build

- name: Create scripts install directory
  file:
    path: "{{ scripts_install_path }}"
    state: directory

- name: Copy terminal-programs binaries
  copy:
    src: "{{ role_path }}/terminal-programs/bin"
    dest: "{{ scripts_install_path }}"
    mode: u+x,g+x,o+x
  when:
    - terminal_programs_build is defined
    - terminal_programs_build.changed
    - not result.terminal_programs_build
