require("config.keys.global.mouse")
require("config.keys.global.tags")
require("config.keys.global.client")
require("config.keys.global.layout")
require("config.keys.global.awesome")
require("config.keys.global.modules")
require("config.keys.global.screen")
