# vi: set ft=yaml.ansible :

- name: Check whether rustup is installed
  ansible.builtin.command: "{{ rust.rustup_bin }} -V"
  register: rust_rustup_installed
  changed_when: false
  failed_when: false

- name: Install rustup
  ansible.builtin.shell: |
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  when: rust_rustup_installed.rc != 0
