# vi: set ft=yaml.ansible :

- name: Install stylua (cargo)
  community.general.cargo:
    name: stylua
    state: present
  when: install

- name: Create stylua config directory
  ansible.builtin.file:
    path: "{{ home_directory }}/.config/stylua"
    state: directory
    mode: u=rwx,g=rx,o=rx

- name: Link stylua config
  ansible.builtin.file:
    src: "{{ role_path }}/stylua.toml"
    dest: "{{ home_directory }}/.config/stylua/stylua.toml"
    state: link
