# vi: set ft=yaml.ansible :

- name: Install stylua (cargo)
  community.general.cargo:
    name: stylua
    state: present
  when: install

- name: Create stylua config directory
  file: 
    path: "{{ home_directory }}/.config/stylua"
    state: directory

- name: Link stylua config
  file:
    src: "{{ role_path }}/stylua.toml"
    dest: "{{ home_directory }}/.config/stylua/stylua.toml"
    state: link
