# vi: set ft=yaml.ansible :

- name: Install hyprland packages (pacman)
  community.general.pacman:
    name:
      - hypridle
      - hyprlock
      - hyprpaper
      - wlogout
    state: present
  become: true
  when:
    - install
    - package_manager == "pacman"

- name: Link hyprland condig
  ansible.builtin.file:
    src: "{{ role_path }}/config"
    dest: "{{ home_directory }}/.config/hypr"
    state: link
