# vim:fileencoding=utf-8:foldmethod=marker

#: Font {{{

font_family      Hack Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 12.0

#}}}

#: Colours {{{

include kanagawa.conf

#}}}

#: Terminal bell {{{

enable_audio_bell no
visual_bell_color none
window_alert_on_bell yes

#: }}}

#: Advanced {{{

startup_session launch.conf

# Need to disable the sudo shell integration as the system rejects TERMINFO env vars
shell_integration no-sudo

#}}}
