# vi: set ft=yaml.ansible :
---

- hosts: arch_laptop
  vars:
    modules:
      # Basics
      - system
      - basic
      - keyboard
      - zsh
      - fonts
      - laptop

      # Programming
      - clang
      - ruby
      - go
      - npm
      - rust

      # Applications
      - X
      - alacritty
      - applications
      - awesome
      - bitwarden
      - common
      - conky
      - git
      - gpg
      - latex
      - neovim
      - rider
      - qutebrowser
      - tmux
      - utilities
      - vifm
  tasks:
    - include_role:
        name: "{{ item }}"
      loop: "{{ modules }}"
  roles:
    - ansible-modules-bitwarden
