---

- hosts: arch_laptop
  vars:
    modules:
      - basic
      - zsh
      - common
      - urxvt
      - fonts
      - tmux
      - X
      - keyboard
      - vim
      - gpg
      - spacemacs
      - awesome
      - clang
      - conky
      - git
      - bitwarden
      - latex
      - qutebrowser
      - ruby
      - laptop
      - go
      - fzf
      - npm
      - vifm
      - rust
      - alacritty
  tasks:
    - include_role:
        name: "{{ item }}"
      loop: "{{ modules }}"
  roles:
    - ansible-modules-bitwarden
