---

- hosts: arch_laptop
  vars:
    roles:
      - basic
      - zsh
      - common
      - urxvt
      - fonts
      - tmux
      - X
      - keyboard
      - vim
      - gpg
      - spacemacs
      - awesome
      - clang
      - conky
      - git
      - lastpass
      - latex
      - qutebrowser
      - ruby
      - laptop
      - go
      - fzf
      - npm
      - vifm
      - rust
      - alacritty
  tasks:
    - include_role:
        name: "{{ item }}"
      loop: "{{ roles }}"
