---

- hosts: flutterbox
  vars:
    modules:
      - basic
      - zsh
      - common
      - fonts
      - tmux
      - X
      - keyboard
      - neovim
      - gpg
      - awesome
      - clang
      - conky
      - git
      - bitwarden
      - latex
      - qutebrowser
      - ruby
      - go
      - npm
      - vifm
      - rust
      - alacritty
      - applications
      - utilities
  tasks:
    - include_role:
        name: "{{ item }}"
      loop: "{{ modules }}"
  roles:
    - ansible-modules-bitwarden
