# vi: set ft=yaml.ansible :
---

- hosts: laptop_hyprland
  vars:
    modules:
      # Basics
      - system
      - basic
      - common
      - pacman
      - zsh
      - zoxide
      - fonts

      # Programming
      - clang
      - lua
      - go
      - npm
      - python
      - rust

      # Applications
      - git
      - gpg
      - neovim
      - tldr
      - utilities
      - vifm
      - zathura
  tasks:
    - include_role:
        name: "{{ item }}"
      loop: "{{ modules }}"
