# vi: set ft=yaml.ansible :
---

- hosts: nuc_arch
  vars:
    modules:
      # Basics
      - system
      - basic
      - zsh
      - zoxide
      - fonts

      # Programming languages
      - clang
      - lua
      - python
      - rust

      # Applications
      - alacritty
      - applications
      - bitwarden
      - common
      - git
      - gpg
      - navi
      - neovim
      - npm
      - obsidian
      - ssh
      - tldr
      - tmux
      - utilities
  tasks:
    - include_role:
        name: "{{ item }}"
      loop: "{{ modules }}"
  roles:
    - ansible-modules-bitwarden
