# vi: set ft=yaml.ansible :
---

- hosts: sintef_wsl
  vars:
    modules:
      # Basics
      - system
      - basic
      - zsh
      - windows_wsl

      # Programming languages
      - clang
      - dotnet
      - go
      - lua
      - npm
      - python
      - ruby
      - rust

      # Applications
      - common
      - git
      - gpg
      - latex
      - navi
      - neovim
      - omnisharp
      - rider
      - svn
      - tldr
      - tmux
      - utilities
      - vifm
      - zoxide
  tasks:
    - include_role:
        name: "{{ item }}"
      loop: "{{ modules }}"
