---

- hosts: sintef_wsl
  vars:
    roles:
      - basic
      - common
      - windows_wsl
      - git
      - svn
      - zsh
      - gpg
      - tmux
      - clang
      - ruby
      - rust
      - npm
      - go
      - fzf
      - thefuck
      - vim
      - vifm
  tasks:
    - include_role:
        name: "{{ item }}"
      loop: "{{ roles }}"
