---

- hosts: sintef_wsl
  vars:
    modules:
      - system
      - basic
      - common
      - windows_wsl
      - git
      - svn
      - zsh
      - gpg
      - tmux
      - clang
      - ruby
      - rust
      - npm
      - go
      - utilities
      - neovim
      - vifm
      - bitwarden
      - dotnet
      - rider
      - omnisharp
      - navi
      - latex
  tasks:
    - include_role:
        name: "{{ item }}"
      loop: "{{ modules }}"
  roles:
    - ansible-modules-bitwarden
