---

- hosts: ubuntu_vbox
  vars:
    roles:
      - basic
      - zsh
      - common
      - urxvt
      - fonts
      - tmux
      - keyboard
      - vim
      - gpg
      - awesome
      - clang
      - git
      - latex
      - lastpass
      - qutebrowser
      - ruby
      - scripts
      - go
      - fzf
      - npm
      - vifm
      - zathura
      - rust
      - alacritty
      - clojure
      - thefuck
  tasks:
    - include_role:
        name: "{{ item }}"
      loop: "{{ roles }}"
