# vi: set ft=yaml.ansible :
---

- hosts: ubuntu_vbox
  vars:
    modules:
      # Basic
      - system
      - basic
      - keyboard
      - zsh
      - fonts

      # Programming languages
      - clang
      - clojure
      - go
      - npm
      - ruby
      - rust

      # Applications
      - alacritty
      - awesome
      - bitwarden
      - common
      - git
      - gpg
      - latex
      - neovim
      - qutebrowser
      - tmux
      - urxvt
      - utilities
      - vifm
      - zathura
  tasks:
    - include_role:
        name: "{{ item }}"
      loop: "{{ modules }}"
  roles:
    - ansible-modules-bitwarden
