---

- hosts: ubuntu_vbox
  vars:
    modules:
      - basic
      - zsh
      - common
      - urxvt
      - fonts
      - tmux
      - keyboard
      - neovim
      - gpg
      - awesome
      - clang
      - git
      - latex
      - bitwarden
      - qutebrowser
      - ruby
      - go
      - npm
      - vifm
      - zathura
      - rust
      - alacritty
      - clojure
      - utilities
  tasks:
    - include_role:
        name: "{{ item }}"
      loop: "{{ modules }}"
  roles:
    - ansible-modules-bitwarden
