---

- hosts: windows_wsl
  vars:
    modules:
      - basic
      - common
      - windows_wsl
      - git
      - zsh
      - gpg
      - tmux
      - clang
      - ruby
      - rust
      - npm
      - go
      - fzf
      - thefuck
      - neovim
      - vifm
      - rider
      - navi
  tasks:
    - include_role:
        name: "{{ item }}"
      loop: "{{ modules }}"
