---

- hosts: windows_wsl
  vars:
    modules:
      - basic
      - common
      - windows_wsl
      - git
      - svn
      - zsh
      - gpg
      - tmux
      - clang
      - ruby
      - rust
      - npm
      - go
      - vim
      - vifm
      - bitwarden
      - rider
      - navi
      - utilities
  tasks:
    - include_role:
        name: "{{ item }}"
      loop: "{{ modules }}"
  roles:
    - ansible-modules-bitwarden
