# vi: set ft=yaml.ansible :
---

- hosts: windows_wsl
  vars:
    modules:
      # Basics
      - system
      - zsh
      - windows_wsl

      # Programming languages
      - lua
      - npm
      - python
      - rust

      # Applications
      - git
      - gpg
      - neovim
      - tldr
      - utilities
      - zoxide
  tasks:
    - include_role:
        name: "{{ item }}"
      loop: "{{ modules }}"
