alias bw-login="source _bw-bin-login-script"
alias bw-unlock="source _bw-bin-unlock-script"
alias pwdfzf="source _pwdfzf-bin-script"
alias pwdshow="source _pwdshow-bin-script"
alias pwdpgp="source _pwdpgp-bin-script"
alias pwdssh="source _pwdssh-bin-script"
