# vi: set ft=yaml.ansible :

- name: Update default vars
  ansible.builtin.set_fact:
    navi: "{{ navi | combine(data.software.navi, recursive=True) }}"
  when: data.software.navi is defined and data.software.navi | default(false)

- name: Make navi config dir
  ansible.builtin.file:
    path: "{{ navi.data_dir }}/cheats"
    state: directory
    mode: u=rwx,g=rx,o=rx

- name: Link navi cheats
  ansible.builtin.file:
    src: "{{ role_path }}/cheats"
    dest: "{{ navi.data_dir }}/cheats/personal"
    state: link
