return {
  {
    "stevearc/dressing.nvim",
    event = "VeryLazy",
  },
  require("irubataru.modules.ui.alpha"),
  require("irubataru.modules.ui.barbecue"),
  require("irubataru.modules.ui.biscuits"),
  require("irubataru.modules.ui.cokeline"),
  require("irubataru.modules.ui.fidget"),
  require("irubataru.modules.ui.illuminate"),
  require("irubataru.modules.ui.limelight"),
  require("irubataru.modules.ui.lualine"),
  require("irubataru.modules.ui.neozoom"),
  require("irubataru.modules.ui.notify"),
  require("irubataru.modules.ui.operator-flashy"),
  require("irubataru.modules.ui.stabilize"),
  require("irubataru.modules.ui.true-zen"),
  require("irubataru.modules.ui.winshift"),
}
