# vi: set ft=yaml.ansible :

- name: Install tldr (cargo)
  community.general.cargo:
    name: tealdeer
    state: present
  when: install

- name: Create tldr config directory
  file: 
    path: "{{ home_directory }}/.local/share/tealdeer"
    state: directory

- name: Link tldr pages directory
  file:
    src: "{{ role_path }}/pages"
    dest: "{{ home_directory }}/.local/share/tealdeer/pages"
    state: link
