# vi: set ft=yaml.ansible :

- name: Update default vars
  ansible.builtin.set_fact:
    qutebrowser: "{{ qutebrowser | combine(data.software.qutebrowser, recursive=True) }}"
  when: data.software.qutebrowser is defined

- name: Install qutebrowser from source (venv)
  ansible.builtin.import_tasks: virtualenv.yml
  when:
    - install
    - package_manager == "apt"

- name: Install qutebrowser from pacman
  ansible.builtin.import_tasks: pacman.yml
  when:
    - install
    - package_manager == "pacman"

- name: Create qutebrowser config directory
  ansible.builtin.file:
    path: "{{ qutebrowser.config_dir }}"
    state: directory
    mode: u=rwx,g=rx,o=rx

- name: Link qutebrowser config files
  ansible.builtin.file:
    src: "{{ role_path }}/{{ link }}"
    dest: "{{ qutebrowser.config_dir }}/{{ link }}"
    state: link
  loop_control:
    loop_var: link
  loop:
    - config.py
    - quickmarks

- name: Check if password_fill exists
  ansible.builtin.stat:
    path: "{{ qutebrowser.global_path }}/userscripts/password_fill"
  register: password_fill_stat

- name: Create userscripts directory
  ansible.builtin.file:
    path: "{{ qutebrowser.scripts_dir }}"
    state: directory
    mode: u=rwx,g=rx,o=rx
    recurse: true
  when: not password_fill_stat.stat.exists

- name: Copy password_fill userscript
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/qutebrowser/qutebrowser/master/misc/userscripts/password_fill"
    dest: "{{ qutebrowser.scripts_dir }}/password_fill"
    mode: "0755"
  when: not password_fill_stat.stat.exists

- name: Install qute-bitwarden dependencies (pipx)
  community.general.pipx:
    name: tldextract
    state: latest
  when: install

- name: Install qute-bitwarden dependencies (apt)
  ansible.builtin.apt:
    name: keyutils
    state: present
  become: true
  when:
    - install
    - package_manager == "apt"

- name: Copy qute-bitwarden userscript
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/qutebrowser/qutebrowser/master/misc/userscripts/qute-bitwarden"
    dest: "{{ qutebrowser.scripts_dir }}/qute-bitwarden"
    mode: "0755"
  when: not password_fill_stat.stat.exists
