- import_tasks: virtualenv.yml
  tags: qutebrowser
  when:
    - install
    - package_manager == "apt"

- import_tasks: pacman.yml
  when:
    - install
    - package_manager == "pacman"

- name: Create qutebrowser config directory
  file:
    path: "{{ qutebrowser_config_path }}"
    state: directory
  tags: qutebrowser

- name: Link qutebrowser config files
  file:
    src: "{{ role_path }}/{{ link }}"
    dest: "{{ qutebrowser_config_path }}/{{ link }}"
    state: link
  loop_control:
    loop_var: link
  loop:
    - config.py
    - quickmarks
  tags: qutebrowser

- name: Check if password_fill exists
  stat:
    path: "{{ qutebrowser_files_path }}/userscripts/password_fill"
  register: password_fill_stat
  tags: qutebrowser

- name: Create userscripts directory
  file:
    path: "{{ qutebrowser_script_path }}"
    state: directory
    recurse: true
  when: not password_fill_stat.stat.exists
  tags: qutebrowser

- name: Copy password_fill userscript
  get_url:
    url: "https://raw.githubusercontent.com/qutebrowser/qutebrowser/master/misc/userscripts/password_fill"
    dest: "{{ qutebrowser_script_path }}/password_fill"
    mode: 0755
  when: not password_fill_stat.stat.exists
  tags: qutebrowser

- name: Install qute-bitwarden dependencies (pip)
  pip:
    name: tldextract
    extra_args: --user
  environment:
    PIP_BREAK_SYSTEM_PACKAGES: 1
  when: install


- name: Install qute-bitwarden dependencies (apt)
  apt:
    name: keyutils
    state: present
  become: true
  when:
    - install
    - package_manager == "apt"


- name: Copy qute-bitwarden userscript
  get_url:
    url: "https://raw.githubusercontent.com/qutebrowser/qutebrowser/master/misc/userscripts/qute-bitwarden"
    dest: "{{ qutebrowser_script_path }}/qute-bitwarden"
    mode: 0755
  when: not password_fill_stat.stat.exists
  tags: qutebrowser
