# vi: set ft=yaml.ansible :

- name: Qutebrowser virtualenv dependencies (apt)
  ansible.builtin.apt:
    name:
      - python3-venv
      - asciidoc
    state: present
  become: true
  when: package_manager == "apt"

- name: Create qutebrowser install directory
  ansible.builtin.file:
    path: "{{ qutebrowser.venv_install_dir }}"
    state: directory
    mode: u=rwx,g=rx,o=rx

- name: Clone qutebrowser repo
  ansible.builtin.git:
    repo: "https://github.com/qutebrowser/qutebrowser.git"
    dest: "{{ qutebrowser.venv_install_dir }}/qutebrowser"
  register: clone_status

- name: Build qutebrowser (virtualenv)
  ansible.builtin.shell: python3 scripts/mkvenv.py
  args:
    chdir: "{{ qutebrowser.venv_install_dir }}/qutebrowser"
  when: clone_status.changed

- name: Create qutebrowser bin directory
  ansible.builtin.file:
    path: "{{ qutebrowser.venv_install_dir }}/bin"
    state: directory
    mode: u=rwx,g=rx,o=rx

- name: Initialise qutebrowser run script
  ansible.builtin.template:
    src: "qutebrowser.j2"
    dest: "{{ qutebrowser.venv_install_dir }}/bin/qutebrowser"
    mode: "0755"
  when: clone_status.changed

- name: Install dictionaries
  ansible.builtin.shell: |
    {{ qutebrowser.venv_install_dir }}/qutebrowser/.venv/bin/python3 \
    {{ qutebrowser.venv_install_dir }}/qutebrowser/scripts/dictcli.py install nb-NO en-GB
  when: clone_status.changed
