# vi: set ft=yaml.ansible :

- name: Install rider from pacman
  ansible.builtin.import_tasks: pacman.yml
  when:
    - install
    - package_manager == "pacman"

- name: "Link ideavim config"
  ansible.builtin.file:
    src: "{{ role_path }}/ideavimrc"
    dest: "{{ home_directory }}/.ideavimrc"
    state: link
