# vi: set ft=yaml.ansible :

- import_tasks: pacman.yml
  when:
    - install
    - package_manager == "pacman"

- name: "Link ideavim config"
  file:
    src: "{{ role_path }}/ideavimrc"
    dest: "{{ home_directory }}/.ideavimrc"
    state: link
