# vi: set ft=yaml.ansible :

- name: Read common vars
  ansible.builtin.include_vars:
    file: ../vars/common.yml
    name: common
  tags:
    - always

- name: Merge data vars
  ansible.builtin.set_fact:
    data: "{{ common.data | combine(data, recursive=True) }}"
  when: data is defined
  tags:
    - always

- name: Set data vars
  ansible.builtin.set_fact:
    data: "{{ common.data }}"
  when: data is not defined
  tags:
    - always

- name: Set global variables
  ansible.builtin.set_fact:
    install: "{{ install | default(false) }}"
    home_directory: "{{ data.user.home_dir }}"
    dotfiles_directory: "{{ data.user.dotfiles_dir | default(data.user.home_dir + '/.dotfiles') }}"
    package_manager: "{{ data.system.package_manager }}"
  tags:
    - always
