- name: Install npm
  pacman:
    name: npm
    state: present

- name: Install terminalizer
  npm:
    name: terminalizer
    global: true
    state: present

- name: Creating terminalizer config directory
  file:
    path: "{{ home_directory }}/.terminalizer"
    state: directory

- name: Link terminalizer config
  file:
    src: "{{ role_path }}/terminalizer.config.yml"
    dest: "{{ home_directory }}/.terminalizer/config.yml"
    state: link
