- import_tasks: pacman.yml
  when: package_manager == "pacman"

- import_tasks: apt.yml
  when: package_manager == "apt"

- name: Link npm config
  file:
    src: "{{ role_path }}/npmrc"
    dest: "{{ home_directory }}/.npmrc"
    state: link

- name: Install terminalizer
  npm:
    name: terminalizer
    global: true
    state: present
  ignore_errors: true

- name: Creating terminalizer config directory
  file:
    path: "{{ home_directory }}/.terminalizer"
    state: directory

- name: Link terminalizer config
  file:
    src: "{{ role_path }}/terminalizer.config.yml"
    dest: "{{ home_directory }}/.terminalizer/config.yml"
    state: link
