# vi: set ft=yaml.ansible :

- name: Update default vars
  ansible.builtin.set_fact:
    vifm: "{{ vifm | combine(data.software.vifm, recursive=True) }}"
  when: data.software.vifm is defined

- name: Import pacman install tasks
  ansible.builtin.import_tasks: pacman.yml
  when:
    - install
    - package_manager == "pacman"

- name: Install vifm (apt)
  ansible.builtin.apt:
    name: vifm
    state: present
  become: true
  when:
    - install
    - package_manager == "apt"

- name: Create vifm config directory
  ansible.builtin.file:
    path: "{{ vifm.config_dir }}"
    state: directory
    mode: u=rwx,g=rx,o=rx

- name: Link vifm config
  ansible.builtin.file:
    src: "{{ role_path }}/vifmrc"
    dest: "{{ vifm.config_dir }}/vifmrc"
    state: link

# - name: Clone colours repo
#   ansible.builtin.git:
#     repo: "https://github.com/vifm/vifm-colors.git"
#     dest: "{{ vifm.config_dir }}/colors"

- name: Create colours directory
  ansible.builtin.file:
    path: "{{ vifm.config_dir }}/colors"
    state: directory
    recurse: true

- name: Add my own colour modifications
  ansible.builtin.file:
    src: "{{ role_path }}/Basically-Default.vifm"
    dest: "{{ vifm.config_dir }}/colors/Basically-Default.vifm"
    state: link
