# vi: set ft=yaml.ansible :

- name: Install vifm (pacman)
  community.general.pacman:
    name: vifm
    state: present
  become: true
  when: package_manager == "pacman"

- name: Install vifmimg and dependencies (AUR)
  kewlfft.aur.aur:
    name:
      - ueberzug
      - ffmpegthumbnailer
      - poppler
      - fontpreview-git
      - fontpreview-ueberzug-git
      - epub-thumbnailer-git
      - vifmimg-git
    state: present
  become: true
  become_user: aur_builder
