# vi: set ft=yaml.ansible :

- name: Update default vars
  ansible.builtin.set_fact:
    clojure: "{{ clojure | combine(data.software.clojure, recursive=True) }}"
  when: data.software.clojure is defined

- name: Installing clojure (apt)
  ansible.builtin.apt:
    name:
      - clojure
      - leiningen
    state: present
  become: true
  when:
    - install
    - package_manager == "apt"

- name: Install clojure (pacman)
  community.general.pacman:
    name: clojure
    state: present
  become: true
  when:
    - install
    - package_manager == "pacman"

- name: Create clojure config directory
  ansible.builtin.file:
    path: "{{ home_directory }}/.config/clojure"
    state: directory
    mode: u=rwx,g=rx,o=rx

- name: Link clojure deps config
  ansible.builtin.file:
    src: "{ role_path}/deps.edn"
    dest: "{{ home_directory }}/.config/clojure/deps.edn"
    state: link

# - name: Create leiningen config directrory
#   file:
#     path: "{{ clojure.lein.config_dir }}"
#     state: directory
#
# - name: Link leiningen config
#   file:
#     src: "{{ role_path }}/lein_profiles.clj"
#     dest: "{{ clojure.lein.config_dir }}/profiles.clj"
#     state: link
