- import_tasks: pacman.yml
  when: package_manager == "pacman"

- name: Link xinitrc
  file:
    src: "{{ role_path }}/xinitrc"
    dest: ~/.xinitrc
    state: link
  ignore_errors: true

- name: Link mimeapps list
  file:
    src: "{{ role_path }}/mimeapps.list"
    dest: ~/.config/mimeapps.list
    state: link
  ignore_errors: true
