- import_tasks: pacman.yml
  when: package_manager == "pacman"

- name: Link xinitrc
  file:
    src: "{{ role_path }}/xinitrc"
    dest: ~/.xinitrc
    state: link
  ignore_errors: true

- name: Initialise Xresources 
  template: 
    src: "Xresources.j2"
    dest: "~/.Xresources"

- name: Link mimeapps list
  file:
    src: "{{ role_path }}/mimeapps.list"
    dest: ~/.config/mimeapps.list
    state: link
  ignore_errors: true

- name: Make handlr config directory
  file:
    path: "{{ home_directory }}/.config/handlr"
    state: directory

- name: Link handlr config
  file:
    src: "{{ role_path }}/handlr.toml"
    dest: ~/.config/handlr/handlr.toml
    state: link
  ignore_errors: true

- name: Create picom config directory directory
  file:
    path: "{{ home_directory }}/.config/picom"
    state: directory

- name: Link picom config
  file:
    src: "{{ role_path }}/picom.conf"
    dest: "{{ home_directory }}/.config/picom/picom.conf"
    state: link

- name: Copy autolock service
  ansible.builtin.copy:
    src: "{{ role_path }}/lock@.service"
    dest: "/etc/systemd/system/lock@.service"
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  become: true

- name: Enable autolock service
  ansible.builtin.systemd:
    name: "lock@{{ user_name }}.service"
    enabled: true
    scope: system
  become: true
