- import_tasks: pacman.yml
  when: package_manager == "pacman"

- name: Link xinitrc
  file:
    src: "{{ role_path }}/xinitrc"
    dest: ~/.xinitrc
    state: link
  ignore_errors: true

- name: Link mimeapps list
  file:
    src: "{{ role_path }}/mimeapps.list"
    dest: ~/.config/mimeapps.list
    state: link
  ignore_errors: true

- name: Link handlr config
  file:
    src: "{{ role_path }}/handlr.toml"
    dest: ~/.config/handlr/handlr.toml
    state: link
  ignore_errors: true

- name: Create picom config directory directory
  file:
    path: "{{ home_directory }}/.config/picom"
    state: directory

- name: Link picom config
  file:
    src: "{{ role_path}}/picom.conf"
    dest: "{{ home_directory }}/.config/picom/picom.conf"
    state: link
