# vi: set ft=yaml.ansible :

- name: Install X utilities (pacman)
  pacman:
    name: 
      - xorg-xset
      - light-locker
      - pinentry
    state: present
  become: true

- name: Install X utilities (AUR)
  kewlfft.aur.aur:
    name:
      - xidlehook-git
      - handlr-bin
      - xdg-utils-handlr
      - picom-git
    state: present
  become: true
  become_user: aur_builder

- name: Install greeter
  kewlfft.aur.aur:
    name: lightdm-webkit-theme-aether
    state: present
  become: true
  become_user: aur_builder
