- name: Install greeter
  kewlfft.aur.aur:
    name: lightdm-webkit-theme-aether
    state: present
  become: true
  become_user: aur_builder

- name: Install X utilities (AUR)
  kewlfft.aur.aur:
    name:
      - xidlehook-git
    state: present
  become: true
  become_user: aur_builder
