qutebrowser:
  global_path: /usr/share/qutebrowser
  config_dir: "{{ home_directory }}/.config/qutebrowser"
  scripts_dir: "{{ home_directory }}/.local/share/qutebrowser/userscripts"
  venv_install_dir: "{{ home_directory }}/.local/"

qutebrowser_files_path: /usr/share/qutebrowser
qutebrowser_config_path: "{{ home_directory }}/.config/qutebrowser"
qutebrowser_script_path: "{{ home_directory }}/.local/share/qutebrowser/userscripts"
qutebrowser_virtualenv_install_root: "{{ home_directory }}/.local/"
