# vi: set ft=yaml.ansible :

- name: Install applications (pacman)
  ansible.builtin.import_tasks: pacman.yml
  when:
    - install
    - package_manager == "pacman"

- name: Link mimeapps list
  ansible.builtin.file:
    src: "{{ role_path }}/mimeapps.list"
    dest: ~/.config/mimeapps.list
    state: link
  ignore_errors: true

- name: Fish configuration
  ansible.builtin.import_tasks: fish.yml
  when:
    - "'fish' in modules"
