- name: Install applications (pacman)
  pacman:
    name:
      - pcmanfm-gtk3
      - vivaldi
      - vivaldi-ffmpeg-codecs
      - mpv
      - mpd
      - cmus
      - discord
    state: present
  become: true

- name: Install applications (AUR)
  kewlfft.aur.aur:
    name:
      - nsxiv
      - spotify
    state: present
  become: true
  become_user: aur_builder
