# vi: set ft=yaml.ansible :
#
- name: Update default vars
  ansible.builtin.set_fact:
    ssh_config: "{{ ssh_config | combine(data.ssh, recursive=True) }}"
  when: data.ssh is defined

- name: Include ssh-agent service tasks
  ansible.builtin.import_tasks: agent.yml
  when:
    - ssh_config.use_agent_socket
    - package_manager == "pacman"

- name: Fish configuration
  ansible.builtin.import_tasks: fish.yml
  when:
    - "'fish' in modules"

- name: Zsh configuration
  ansible.builtin.import_tasks: zsh.yml
  when:
    - "'zsh' in modules"
