# vi: set ft=yaml.ansible :

- name: Create systemd directory
  ansible.builtin.file:
    path: "{{ home_directory }}/.config/systemd/user"
    state: directory
    mode: u=rwx,g=rx,o=rx

- name: Link ssh-agent service
  ansible.builtin.file:
    src: "{{ role_path }}/ssh-agent.service"
    dest: "{{ home_directory }}/.config/systemd/user/ssh-agent.service"
    state: link

- name: Enable ssh-agent service
  ansible.builtin.systemd:
    name: "ssh-agent.service"
    enabled: true
    scope: user
