# vi: set ft=yaml.ansible :

- name: Initialise the path template
  ansible.builtin.template:
    src: "path.zsh.j2"
    dest: "{{ role_path }}/path.zsh"
    mode: u=rw,g=r,o=r

- name: Set ssh_keys variable
  ansible.builtin.set_fact:
    ssh_keys: "{{ data.ssh.key_config }}"
  when: data.ssh.key_config is defined

- name: Initialise ssh-add-all script
  ansible.builtin.template:
    src: "ssh-add-all.j2"
    dest: "{{ role_path }}/bin/ssh-add-all"
    mode: u=rwx,g=rx,o=rx
  when:
    - ssh_keys is defined
    - ssh_keys | length > 0
