# vi: set ft=yaml.ansible :

- name: Install zoxide (cargo)
  community.general.cargo:
    name: zoxide
    state: present
  when: install

- name: Fish configuration
  ansible.builtin.import_tasks: fish.yml
  when:
    - "'fish' in modules"
