# vi: set ft=yaml.ansible :

- name: Install atuin (pacman)
  community.general.pacman:
    name: atuin
    state: present
  become: true
  when:
    - install
    - package_manager == "pacman"

- name: Create atuin config directory
  ansible.builtin.file:
    path: "{{ home_directory }}/.config/atuin"
    state: directory
    mode: u=rwx,g=rx,o=rx

- name: Link atuin configuration
  ansible.builtin.file:
    src: "{{ role_path }}/atuin.config.toml"
    dest: "{{ home_directory }}/.config/atuin/config.toml"
    state: link
    force: true
