# vi: set ft=yaml.ansible :

- name: Update default vars
  ansible.builtin.set_fact:
    zsh: "{{ zsh | combine(data.zsh, recursive=True) }}"
  when: data.zsh is defined

- name: Install zsh (pacman)
  community.general.pacman:
    name: zsh
    state: present
  become: true
  when:
    - install
    - package_manager == "pacman"

- name: Install zsh (apt)
  ansible.builtin.apt:
    name: zsh
    state: present
  become: true
  when:
    - install
    - package_manager == "apt"

- name: Backup old zsh config file
  ansible.builtin.copy:
    src: "{{ home_directory }}/.zshrc"
    dest: "{{ home_directory }}/.zshrc.bak"

- name: Copy zsh config file
  ansible.builtin.template:
    src: "zshrc.j2"
    dest: "~/.zshrc"
    mode: u=rw,g=r,o=r

- name: Copy zsh fpath config file
  ansible.builtin.template:
    src: "fpath.zsh.j2"
    dest: "{{ role_path }}/fpath.zsh"
    mode: u=rw,g=r,o=r

- name: Change user default shell
  ansible.builtin.user:
    name: "{{ data.user.username }}"
    shell: /bin/zsh
  become: true

- name: Initialise argcomplete if it doesn't exist
  ansible.builtin.shell:
    cmd: |
      activate-global-python-argcomplete --dest {{ role_path }}
      mv {{ role_path }}/_python-argcomplete {{ role_path }}/argcomplete.zsh
    creates: "{{ role_path }}/argcomplete.zsh"
