# vi: set ft=yaml.ansible :

- name: Install zsh (pacman)
  pacman:
    name: zsh
    state: present
  become: true
  when: package_manager == "pacman"

- name: Install zsh (apt)
  apt:
    name: zsh
    state: present
  become: true
  when: package_manager == "apt"

- name: Copy zsh config file
  ansible.builtin.template:
    src: "zshrc.j2"
    dest: "~/.zshrc"

- name: Copy zsh fpath config file
  ansible.builtin.template: 
    src: "fpath.zsh.j2"
    dest: "{{ role_path }}/fpath.zsh"

- name: Copy dircolor zsh file
  ansible.builtin.template: 
    src: "dircolor.zsh.j2"
    dest: "{{ role_path }}/dircolor.zsh"

- name: Link spaceship config
  ansible.builtin.file:
    src: "{{role_path}}/starship.toml"
    dest: "~/.config/starship.toml"
    state: link

- include_tasks: atuin.yml
  when: zinit.plugins.atuin

- name: Change user default shell
  user:
    name: "{{ user_name }}"
    shell: /bin/zsh
  become: true
