- name: Install zsh (pacman)
  pacman:
    name: zsh
    state: present
  become: true
  when: package_manager == "pacman"

- name: Install zsh (apt)
  apt:
    name: zsh
    state: present
  become: true
  when: package_manager == "apt"

- name: Copy zsh config file
  template:
    src: "zshrc.j2"
    dest: "~/.zshrc"

- name: Copy zsh fpath config file
  template: 
    src: "fpath.zsh.j2"
    dest: "{{ role_path }}/fpath.zsh"

- name: Copy dircolor zsh file
  template: 
    src: "dircolor.zsh.j2"
    dest: "{{ role_path }}/dircolor.zsh"

- include_tasks: oh-my-zsh.yml
  when: oh_my_zsh.use

- name: Change user default shell
  user:
    name: user_name
    shell: /bin/zsh
  become: true
