- name: Copy zsh config file
  template:
    src: "zshrc.j2"
    dest: "~/.zshrc"

- name: Copy zsh fpath config file
  template: 
    src: "fpath.zsh.j2"
    dest: "{{ role_path }}/fpath.zsh"

- name: Copy dircolor zsh file
  template: 
    src: "dircolor.zsh.j2"
    dest: "{{ role_path }}/dircolor.zsh"

- include_tasks: oh-my-zsh.yml
  when: oh_my_zsh.use
