# vi: set ft=yaml.ansible :

- name: Install zsh (pacman)
  pacman:
    name: zsh
    state: present
  become: true
  when:
    - install
    - package_manager == "pacman"

- name: Install zsh (apt)
  apt:
    name: zsh
    state: present
  become: true
  when:
    - install
    - package_manager == "apt"

- name: Copy zsh config file
  ansible.builtin.template:
    src: "zshrc.j2"
    dest: "~/.zshrc"

- name: Copy zsh fpath config file
  ansible.builtin.template: 
    src: "fpath.zsh.j2"
    dest: "{{ role_path }}/fpath.zsh"

- name: Link spaceship config
  ansible.builtin.file:
    src: "{{role_path}}/starship.toml"
    dest: "~/.config/starship.toml"
    state: link

- include_tasks: atuin.yml
  when: zsh.plugins.atuin

- name: Change user default shell
  user:
    name: "{{ user_name }}"
    shell: /bin/zsh
  become: true

- name: Initialise argcomplete if it doesn't exist
  ansible.builtin.shell:
    cmd: |
      activate-global-python-argcomplete --dest {{role_path}}
      mv {{role_path}}/_python-argcomplete {{role_path}}/argcomplete.zsh
    creates: "{{ role_path }}/argcomplete.zsh"
