- name: Cloning oh-my-zsh repo
  git:
    repo: "https://github.com/robbyrussell/oh-my-zsh.git"
    dest: "{{ oh_my_zsh.directory }}"
  register: clone_result

- name: Getting additional oh-my-zsh themes
  get_url:
    url: "{{ theme.url }}"
    dest: "{{ oh_my_zsh.directory }}/themes/{{ theme.target }}"
  loop_control:
    loop_var: theme
  loop:
    - {
        url: "https://raw.githubusercontent.com/shashankmehta/dotfiles/master/thesetup/zsh/.oh-my-zsh/custom/themes/gitster.zsh-theme",
        target: "gitster.zsh-theme"
      }
    - {
        url: "https://raw.githubusercontent.com/halfo/lambda-mod-zsh-theme/master/lambda-mod.zsh-theme",
        target: "lambda-mod.zsh-theme"
      }
    - {
        url: "https://raw.githubusercontent.com/denysdovhan/spaceship-zsh-theme/master/spaceship.zsh",
        target: "spaceship.zsh"
      }
    - {
        url: "https://raw.githubusercontent.com/skylerlee/zeta-zsh-theme/master/zeta.zsh-theme",
        target: "zeta.zsh-theme"
      }
    - {
        url: "https://raw.githubusercontent.com/lenguyenthanh/nt9-oh-my-zsh-theme/master/nt9.zsh-theme",
        target: "nt9.zsh-theme"
      }

- name: Downloading powerlevel10k theme
  git:
    repo: "https://github.com/romkatv/powerlevel10k.git"
    dest: "{{ oh_my_zsh.directory }}/custom/themes/powerlevel10k"
    depth: 1
  register: p10k_init

- name: Link powerlevel10k config
  file:
    src: "{{ role_path }}/p10krc"
    dest: "{{ home_directory }}/.p10k.zsh"
    state: link
  when: 
    - not p10k_init.failed
