# vi: set ft=yaml.ansible :

- name: Install gtk themes (aur)
  kewlfft.aur.aur:
    name:
      - rose-pine-gtk-theme-full
      - nordic-theme
      - rose-pine-cursor
      - rose-pine-hyprcursor
    state: present
  become: true
  become_user: aur_builder
  when:
    - install
    - package_manager == "pacman"

- name: Create gtk config directory
  ansible.builtin.file:
    path: "{{ home_directory }}/.config/gtk-3.0"
    state: directory
    mode: u=rwx,g=rx,o=rx

- name: Link gtk settings
  ansible.builtin.file:
    src: "{{ role_path }}/gtk-3.0-settings.ini"
    dest: "{{ home_directory }}/.config/gtk-3.0/settings.ini"
    state: link
