# vi: set ft=yaml.ansible :

- name: Add scripts to path
  ansible.builtin.template:
    src: "path.zsh.j2"
    dest: "{{ role_path }}/path.zsh"
    mode: u=rw,g=r,o=r

- name: Tasks for Omegapoint HP Elitebook
  ansible.builtin.import_tasks: omegapoint-hp-elitebook.yml
  when:
    - data.system.hardware is defined
    - data.system.hardware == "omegapoint-hp-elitebook"

- name: Tasks for the Lofree Keyboard
  ansible.builtin.import_tasks: lofree-keyboard.yml
  when:
    - data.system.accessories is defined
    - "'lofree_keyboard' in data.system.accessories"
