- name: Add scripts to path
  ansible.builtin.template:
    src: "path.zsh.j2"
    dest: "{{ role_path }}/path.zsh"
    mode: u=rw,g=r,o=r

- name: Tasks for Omegapoint HP Elitebook
  ansible.builtin.import_tasks: omegapoint-hp-elitebook.yml
  when:
    - hardware == omegapoint-hp-elitebook
