- name: Install applications (pacman)
  pacman:
    name:
      - pcmanfm-gtk3
      - zathura
      - zathura-pdf-mupdf
      - zathura-ps
      - zathura-djvu
      - vivaldi
      - vivaldi-ffmpeg-codecs
      - mpv
      - mpd
      - cmus
      - discord
    state: present
  become: true

- name: Install applications (AUR)
  kewlfft.aur.aur:
    name:
      - steam
    state: present
  become: true
  become_user: aur_builder
