#!/usr/bin/python3
# -*- coding: utf-8 -*-
"""
"""

import sys


def main(args):
    """
    """

    %HERE%



if __name__ == "__main__":
    try:
        main(sys.argv)
    except KeyboardInterrupt:
        print("\nProgram interrupted by user")
