- name: Install clang packages (apt)
  ansible.builtin.import_tasks: apt.yml
  when:
    - install
    - package_manager == "apt"

- name: Link clang-format
  ansible.builtin.file:
    src: "{{ role_path }}/clang-format"
    dest: "~/.clang-format"
    state: link
