# vi: set ft=yaml.ansible :

- name: Set GNOME keybinds
  ansible.builtin.import_tasks: keybinds.yml

- name: Link reset-keybinds script
  ansible.builtin.file:
    src: "{{ role_path }}/systemd/reset-tiling-keys.bash"
    dest: "{{ home_directory }}/.local/bin/reset-tiling-keys.bash"
    state: link

- name: Create systemd directory
  ansible.builtin.file:
    path: "{{ home_directory }}/.config/systemd/user"
    state: directory
    mode: u=rwx,g=rx,o=rx

- name: Link tiling-key service
  ansible.builtin.file:
    src: "{{ role_path }}/systemd/tiling-keys.service"
    dest: "{{ home_directory }}/.config/systemd/user/tiling-keys.service"
    state: link

- name: Enable tiling-keys service
  ansible.builtin.systemd:
    name: "tiling-keys.service"
    enabled: true
    scope: user
