- name: Installing basic dependencies (pacman)
  community.general.pacman:
    name:
      - clang
      - python
      - python-pip
      - python-pipx
      - unzip
      - fontconfig
      - fakeroot
      - make
      - cmake
    state: present
  become: true
  when: package_manager == "pacman"

- name: Create the `aur_builder` user
  ansible.builtin.user:
    name: aur_builder
    create_home: yes
    home: /home/.aur_builder
    group: wheel
  become: yes

- name: Allow the `aur_builder` user to run `sudo pacman` without a password
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    validate: 'visudo -cf %s'
  become: yes

- name: Install paru aur manager
  kewlfft.aur.aur:
    name: paru
    state: present
  become: yes
  become_user: aur_builder
