# vi: set ft=yaml.ansible :

- name: Update default vars
  ansible.builtin.set_fact:
    git: "{{ git | combine(data.git, recursive=True) }}"
  when: data.git is defined

- name: Install git packages (pacman)
  ansible.builtin.import_tasks: pacman.yml
  when:
    - install
    - package_manager == "pacman"

- name: Install git packages (apt)
  ansible.builtin.import_tasks: apt.yml
  when:
    - install
    - package_manager == "apt"

- name: Install git-stack (cargo)
  community.general.cargo:
    name:
      - git-stack
      - git-branch-stash-cli
    state: present
    locked: true
  when: install

- name: Link default gitignore
  ansible.builtin.file:
    src: "{{ role_path }}/gitignore"
    dest: "~/.gitignore"
    state: link

- name: Initialise gitconfig
  ansible.builtin.template:
    src: "gitconfig.j2"
    dest: "~/.gitconfig"
    mode: u=rw,g=r,o=r

- name: Link tig config file
  ansible.builtin.file:
    src: "{{ role_path }}/tigrc"
    dest: "~/.tigrc"
    state: link

- name: Space Norway configuration
  ansible.builtin.import_tasks: spn.yml
  when: data.system.work == "spn"

- name: Fish configuration
  ansible.builtin.import_tasks: fish.yml
  when:
    - "'fish' in modules"

- name: Zsh configuration
  ansible.builtin.import_tasks: zsh.yml
  when:
    - "'zsh' in modules"
