- import_tasks: pacman.yml
  when:
    - install
    - package_manager == "pacman"

# - import_tasks: apt.yml
#   when: package_manager == "apt"

- name: "Clone the note repo"
  git:
    repo: "git@github.com:Irubataru/obsidian-notes.git"
    dest: "{{ obsidian.directory }}"
    update: false
  ignore_errors: true
