# vi: set ft=yaml.ansible :

- name: Update default vars
  ansible.builtin.set_fact:
    obsidian: "{{ obsidian | combine(data.software.obsidian, recursive=True) }}"
  when: data.software.obsidian is defined

- name: Install obsidian from pacman
  ansible.builtin.import_tasks: pacman.yml
  when:
    - install
    - package_manager == "pacman"

# - import_tasks: apt.yml
#   when: package_manager == "apt"

- name: "Clone the note repo"
  ansible.builtin.git:
    repo: "git@github.com:Irubataru/obsidian-notes.git"
    dest: "{{ obsidian.directory }}"
    update: false
  ignore_errors: true
