- import_tasks: apt.yml
  when: package_manager == "apt"

- name: Download lastpass zsh completion
  get_url:
    url: "https://raw.githubusercontent.com/lastpass/lastpass-cli/master/contrib/lpass_zsh_completion"
    dest: "{{ role_path }}/_lpass"

- name: Install lastpass-ansible gem
  gem:
    name: lastpass-ansible
    state: latest

- name: Link lastpass-ansible config
  file:
    src: "{{ role_path }}/lastpass-ansible.conf"
    dest: "{{ dotfiles_directory }}/.lastpass-ansible.conf"
    state: link
