# vi: set ft=yaml.ansible :

- name: Update default vars
  ansible.builtin.set_fact:
    wezterm: "{{ wezterm | combine(data.software.wezterm, recursive=True) }}"
  when: data.software.wezterm is defined

- name: Import tasks for pacman
  ansible.builtin.import_tasks: pacman.yml
  when:
    - install
    - package_manager == "pacman"

- name: Link wezterm config
  ansible.builtin.file:
    src: "{{ role_path }}/config"
    dest: "{{ home_directory }}/.config/wezterm"
    state: link
