# vi: set ft=yaml.ansible :

- import_tasks: pacman.yml
  when:
    - install
    - package_manager == "pacman"

- name: Link wezterm config
  ansible.builtin.file:
    src: "{{ role_path }}/config"
    dest: "{{ home_directory }}/.config/wezterm"
    state: link
