# vi: set ft=yaml.ansible :

- name: Install wezterm (AUR)
  kewlfft.aur.aur:
    name: wezterm-git
    state: present
  become: true
  become_user: aur_builder
  when: wezterm.install_from_git

- name: Install wezterm (pacman)
  community.general.pacman:
    name: wezterm
    state: present
  become: true
  when: not wezterm.install_from_git
