- import_tasks: apt.yml
  when:
    - install
    - package_manager == "apt"

- import_tasks: pacman.yml
  when:
    - install
    - package_manager == "pacman"


- name: Zathura config directory
  file: 
    path: "{{ home_directory }}/.config/zathura"
    state: directory

- name: Link zathura config
  file:
    src: "{{ role_path }}/zathurarc"
    dest: "{{ home_directory }}/.config/zathura/zathurarc"
    state: link
