# vi: set ft=yaml.ansible :

- name: Install zathura (pacman)
  community.general.pacman:
    name:
      - zathura
      - zathura-pdf-mupdf
      - zathura-ps
      - zathura-djvu
    state: present
  become: true
