# vi: set ft=yaml.ansible :

- name: Copy personal keymap
  ansible.builtin.copy:
    src: "{{ role_path }}/jp2.keymap"
    dest: /usr/share/X11/xkb/symbols/jp2
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  become: true
