# vi: set ft=yaml.ansible :

- name: Install rofi from pacman
  ansible.builtin.import_tasks: pacman.yml
  when:
    - install
    - package_manager == "pacman"

# - import_tasks: apt.yml
#   when: package_manager == "apt"

- name: Link rofi configuration director
  ansible.builtin.file:
    src: "{{ role_path }}/config"
    dest: "{{ home_directory }}/.config/rofi"
    state: link

- name: Link rofimoji configuratin
  ansible.builtin.file:
    src: "{{ role_path }}/rofimoji.rc"
    dest: "{{ home_directory }}/.config/rofimoji.rc"
    state: link
