# vi: set ft=yaml.ansible :


- name: Install mpd packages (pacman)
  ansible.builtin.import_tasks: pacman.yml
  when:
    - install
    - package_manager == "pacman"

- name: Install mpd packages (apt)
  ansible.builtin.import_tasks: apt.yml
  when:
    - install
    - package_manager == "apt"

- name: Create mpd config directory
  ansible.builtin.file:
    path: "{{ home_directory }}/.config/mpd"
    state: directory
    mode: u=rwx,g=rx,o=rx

- name: Link mpd config
  ansible.builtin.file:
    src: "{{ role_path }}/mpd.conf"
    dest: "{{ home_directory }}/.config/mpd/mpd.conf"
    state: link

- name: Create ncmpcpp config directory
  ansible.builtin.file:
    path: "{{ home_directory }}/.config/ncmpcpp"
    state: directory
    mode: u=rwx,g=rx,o=rx

- name: Link ncmpcpp config
  ansible.builtin.file:
    src: "{{ role_path }}/ncmpcpp.config"
    dest: "{{ home_directory }}/.config/ncmpcpp/config"
    state: link

- name: Create mpd directory
  ansible.builtin.file:
    path: "{{ home_directory }}/.mpd"
    state: directory
    mode: u=rwx,g=rx,o=rx

- name: Create mpd/playlists directory
  ansible.builtin.file:
    path: "{{ home_directory }}/.mpd/playlists"
    state: directory
    mode: u=rwx,g=rx,o=rx

- name: Enable mpd service
  ansible.builtin.systemd:
    name: "mpd.service"
    enabled: true
    scope: user
  when: package_manager == "pacman"

- name: Enable mpd-mpris service
  ansible.builtin.systemd:
    name: "mpd-mpris.service"
    enabled: true
    scope: user
  when: package_manager == "pacman"
