# vi: set ft=yaml.ansible :

- name: Install tmux (pacman)
  community.general.pacman:
    name: tmux
    state: present
  become: true
  when:
    - install
    - package_manager == "pacman"

- name: Install tmux (apt)
  ansible.builtin.apt:
    name: tmux
    state: present
  become: true
  when:
    - install
    - package_manager == "apt"

- name: Link tmux config file
  ansible.builtin.file:
    src: "{{ role_path }}/tmux.conf"
    dest: "~/.tmux.conf"
    state: link

- name: Create tmux plugins directory
  ansible.builtin.file:
    path: "{{ home_directory }}/.tmux/plugins"
    state: directory
    mode: u=rwx,g=rx,o=rx

- name: Get Tmux Plugin Manager
  ansible.builtin.git:
    repo: "https://github.com/tmux-plugins/tpm"
    dest: "{{ home_directory }}/.tmux/plugins/tpm"
