- import_tasks: pacman.yml
  when: system == "arch-laptop"

- import_tasks: apt.yml
  when: system == "windows-wsl"

- name: Link tmux config file
  file:
    src: "{{ role_path }}/tmux.conf"
    dest: "~/.tmux.conf"
    state: link
