- name: Install tmux (pacman)
  pacman:
    name: tmux
    state: present
  become: true
  when: package_manager == "pacman"

- name: Install tmux (apt)
  apt:
    name: tmux
    state: present
  become: true
  when: package_manager == "apt"

- name: Link tmux config file
  file:
    src: "{{ role_path }}/tmux.conf"
    dest: "~/.tmux.conf"
    state: link

- name: Create tmux plugins directory
  file: 
    path: "{{ home_directory }}/.tmux/plugins"
    state: directory

- name: Get Tmux Plugin Manager
  git:
    repo: "https://github.com/tmux-plugins/tpm"
    dest: "{{ home_directory }}/.tmux/plugins/tpm"
