# vi: set ft=yaml.ansible :

- name: Install waybar and dependencies (pacman)
  community.general.pacman:
    name:
      - waybar
      - swaync # Notification panel
    state: present
  become: true
  when:
    - install
    - package_manager == "pacman"

- name: Install waybar dependencies (aur)
  kewlfft.aur.aur:
    name:
      - wlogout # Logout menu
    state: present
  become: true
  become_user: aur_builder
  when:
    - install
    - package_manager == "pacman"

- name: Link waybar config
  ansible.builtin.file:
    src: "{{ role_path }}/config"
    dest: "{{ home_directory }}/.config/waybar"
    state: link

- name: Link swaync config
  ansible.builtin.file:
    src: "{{ role_path }}/swaync"
    dest: "{{ home_directory }}/.config/swaync"
    state: link

- name: Link wlogout config
  ansible.builtin.file:
    src: "{{ role_path }}/wlogout"
    dest: "{{ home_directory }}/.config/wlogout"
    state: link
