- name: Install urxvt (pacman)
  pacman:
    name: rxvt-unicode
    state: present
  become: true
  when: package_manager == "pacman"

- name: Install urxvt (apt)
  pacman:
    name: rxvt-unicode
    state: present
  become: true
  when: package_manager == "pacman"

- name: Initialise Xresources 
  template: 
    src: "Xresources.j2"
    dest: "~/.Xresources"
  register: xresource_init

- name: Reload Xresources if it has changed
  shell: xrdb ~/.Xresources
  when: xresource_init.changed
