# vi: set ft=yaml.ansible :

- name: Update default vars
  ansible.builtin.set_fact:
    urxvt: "{{ urxvt | combine(data.software.urxvt, recursive=True) }}"
  when: data.software.urxvt is defined

- name: Install urxvt (pacman)
  community.general.pacman:
    name: rxvt-unicode
    state: present
  become: true
  when:
    - install
    - package_manager == "pacman"

- name: Install urxvt (apt)
  ansible.builtin.apt:
    name: rxvt-unicode
    state: present
  become: true
  when:
    - install
    - package_manager == "apt"

- name: Initialise Xresources
  ansible.builtin.template:
    src: "Xresources.j2"
    dest: "~/.Xresources"
    mode: u=rwx,g=rx,o=rx
  register: xresource_init

- name: Reload Xresources if it has changed
  ansible.builtin.shell: xrdb ~/.Xresources
  when: xresource_init.changed
