# vi: set ft=yaml.ansible :

- name: Pacman install
  ansible.builtin.import_tasks: pacman.yml
  when:
    - package_manager == "pacman"

- name: Apt install
  ansible.builtin.import_tasks: apt.yml
  when:
    - package_manager == "apt"

- name: Install bat, cargo-update, clock-tui, rip-cli (cargo)
  community.general.cargo:
    name:
      - bat
      - cargo-update
      - clock-tui
      - rip-cli
    state: present
    locked: true
  when: install

- name: Import tasks for installing bat
  ansible.builtin.import_tasks: bat.yml

- name: Fish configuration
  ansible.builtin.import_tasks: fish.yml
  when:
    - "'fish' in modules"
