- name: Install Ubuntu software properties
  apt:
    name: software-properties-common
    state: present
  become: true

- name: Add neovim development ppa
  apt_repository:
    repo: ppa:neovim-ppa/unstable

- name: Install neovim
  apt:
    name:
      - python-dev
      - python-pip
      - python3-dev
      - python3-pip
      - neovim
    state: present
  become: true

# TODO Install ccls
