- name: Install neovim
  pacman:
    name: neovim
    state: present
  become: true

- name: Install neovim python provider
  pip:
    name: pynvim
    extra_args: --user
    state: latest

- name: Install neovim ruby provider
  gem:
    name: neovim
    user_install: true
    state: latest

# TODO Install ccls
