- name: Create vim temp storage directory
  file: 
    path: "{{ home_directory }}/.tmp"
    state: directory

- name: Link vim dotfiles
  file:
    src: "{{ role_path }}/config"
    dest: "{{ home_directory }}/.vim"
    state: link
