- name: Install alacritty build dependencies (apt)
  apt:
    name: 
      - cmake
      - pkg-config
      - libfreetype6-dev
      - libfontconfig1-dev
      - libxcb-xfixes0-dev
      - python3
    state: present
  become: true
