- import_tasks: apt.yml
  when:
    - install
    - package_manager == "apt" 

- import_tasks: pacman.yml
  when:
    - install
    - package_manager == "pacman"

- import_tasks: install_from_git.yml
  when:
    - install
    - package_manager == "apt"

- name: Create alacritty config directory
  file: 
    path: "{{ alacritty_config_path }}"
    state: directory

- name: Link alacritty config
  file:
    src: "{{ role_path }}/alacritty.toml"
    dest: "{{ alacritty_config_path }}/alacritty.toml"
    state: link

- name: Link alacritty config (legacy)
  file:
    src: "{{ role_path }}/alacritty.yml"
    dest: "{{ alacritty_config_path }}/alacritty.yml"
    state: link

- name: Add GL3 fix
  template: 
    src: "libgl_fix.zsh.j2"
    dest: "{{ home_directory }}/.local/bin/alacritty"
    mode: u=rx,g=rx,o=rx
  when: alacritty_gl3_fix
