- name: Install alacritty X dependencies (pacman)
  pacman:
    name: 
      - cmake
      - freetype2
      - fontconfig
      - pkg-config
      - make
      - libxcb
      - libxkbcommon
      - python
    state: present
  become: true

- name: Install alacritty (pacman)
  kewlfft.aur.aur:
    name: alacritty-git
    state: present
  become: yes
  become_user: aur_builder
