- name: Install gpg (pacman)
  pacman:
    name: gnupg
    state: present
  become: true
  when: package_manager == "pacman"

- name: Install gpg (apt)
  apt:
    name:
      - gnupg
      - scdaemon
    state: present
  become: true
  when: package_manager == "apt"

- name: Import keys
  shell: "gpg --import {{ role_path }}/pubkey"

- name: Set GPG TTY
  template: 
    src: "tty.zsh.j2"
    dest: "{{ role_path }}/tty.zsh"
  when: hw_cmd_only
