# vi: set ft=yaml.ansible :

- name: Install gpg (pacman)
  community.general.pacman:
    name: gnupg
    state: present
  become: true
  when:
    - install
    - package_manager == "pacman"

- name: Install gpg (apt)
  ansible.builtin.apt:
    name:
      - gnupg
      - scdaemon
    state: present
  become: true
  when:
    - install
    - package_manager == "apt"

- name: Import keys
  ansible.builtin.shell: "gpg --import {{ role_path }}/pubkey"

- name: Set GPG TTY
  ansible.builtin.template:
    src: "tty.zsh.j2"
    dest: "{{ role_path }}/tty.zsh"
    mode: u=rw,g=r,o=r
  when: data.system.has_display | default(false)
