# vi: set ft=yaml.ansible :

- name: Install playerctl from pacman
  ansible.builtin.import_tasks: pacman.yml
  when:
    - install
    - package_manager == "pacman"

- name: Link playerctld service
  ansible.builtin.file:
    src: "{{ role_path }}/playerctld.service"
    dest: "{{ home_directory }}/.config/systemd/user/playerctld.service"
    state: link

- name: Enable playerctld service
  ansible.builtin.systemd:
    name: "playerctld.service"
    enabled: true
    scope: user
