- import_tasks: apt.yml
  when: package_manager == "apt"

- include_tasks: xelatex.yml
  when: latex_use_xelatex

- name: Creating latex beamer theme directory
  file:
    path: "{{ home_directory }}/.texmf/tex/latex/beamer"
    state: directory

- name: Cloning latex beamer themes
  git:
    repo: "https://github.com/Irubataru/beamer-themes.git"
    dest: "{{ home_directory }}/.texmf/tex/latex/beamer/theme"
