# vi: set ft=yaml.ansible :

- name: Configure Archlinux laptop
  hosts: localhost
  connection: local
  vars_files:
    - ../vars/arch-laptop.yml
  vars:
    modules:
      # Basics
      - system
      - basic
      - pacman
      - keyboard
      - zsh
      - zoxide
      - fonts
      - laptop

      # Programming
      - clang
      - clojure
      - ruby
      - lua
      - go
      - npm
      - python
      - rust

      # Applications
      - X
      - alacritty
      - applications
      - awesome
      - common
      - conky
      - git
      - gpg
      - gtk
      - latex
      - navi
      - neovim
      - obsidian
      - rider
      - qutebrowser
      - rofi
      - tldr
      - tmux
      - utilities
      - vifm
      - zathura
  pre_tasks:
    - name: Merge variables
      ansible.builtin.include_tasks: ../tasks/merge_vars.yml
      tags:
        - always
  tasks:
    # - name: "Print modules"
    #   ansible.builtin.debug:
    #     var: modules
    # - name: "Print data"
    #   ansible.builtin.debug:
    #     var: data
    - name: Run all modules
      ansible.builtin.include_role:
        apply:
          tags:
            - "{{ item }}"
        name: "{{ item }}"
      loop: "{{ modules }}"
      tags:
        - always
