# vi: set ft=yaml.ansible :

- name: Run debug playbook
  hosts: localhost
  connection: local
  vars_files:
    - ../vars/debug.yml
  pre_tasks:
    - name: Merge variables
      ansible.builtin.include_tasks: ../tasks/merge_vars.yml
  vars:
    modules:
      - debug
  tasks:
    - name: "Print modules"
      ansible.builtin.debug:
        var: modules
    - name: "Print data"
      ansible.builtin.debug:
        var: data
    - name: Run all modules
      ansible.builtin.include_role:
        name: "{{ item }}"
      loop: "{{ modules }}"
