# vi: set ft=yaml.ansible :

- name: Configure Flutterbox
  hosts: localhost
  connection: local
  vars_files:
    - ../vars/flutterbox.yml
  vars:
    modules:
      # Basics
      - system
      - basic
      - pacman
      - keyboard
      - zsh
      - zoxide
      - fonts

      # Programming languages
      - clang
      - lua
      - go
      - npm
      - python
      - rust

      # Applications
      - X
      - wezterm
      - applications
      - awesome
      - clang
      - common
      - git
      - gpg
      - gtk
      - latex
      - navi
      - neovim
      - obsidian
      - rider
      - rofi
      - tldr
      - tmux
      - utilities
      - vifm
      - zathura
  pre_tasks:
    - name: Merge variables
      ansible.builtin.include_tasks: ../tasks/merge_vars.yml
  tasks:
    - name: Run all modules
      ansible.builtin.include_role:
        name: "{{ item }}"
      loop: "{{ modules }}"
