# vi: set ft=yaml.ansible :

- name: Configure NUC with archlinux
  hosts: localhost
  connection: local
  vars_files:
    - ../vars/nuc-arch.yml
  pre_tasks:
    - name: Merge variables
      ansible.builtin.include_tasks: ../tasks/merge_vars.yml
  vars:
    modules:
      # Basics
      - system
      - basic
      - pacman
      - zsh
      - zoxide
      - fonts

      # Programming languages
      - clang
      - lua
      - python
      - rust

      # Applications
      - alacritty
      - applications
      - common
      - git
      - gpg
      - navi
      - neovim
      - npm
      - obsidian
      - ssh
      - tldr
      - tmux
      - utilities
  tasks:
    - name: Run all modules
      ansible.builtin.include_role:
        name: "{{ item }}"
      loop: "{{ modules }}"
