# vi: set ft=yaml.ansible :

- name: Configure Omegapoint laptop
  hosts: localhost
  connection: local
  vars_files:
    - ../vars/omegapoint.yml
  pre_tasks:
    - name: Merge variables
      ansible.builtin.include_tasks: ../tasks/merge_vars.yml
  vars:
    modules:
      # Basics
      - system
      - basic
      - keyboard
      - bluetooth
      - zsh
      - zoxide
      - fonts
      - laptop

      # Window manager
      - wayland
      - hyprland
      - waybar

      # Programming languages
      - clang
      - dotnet
      - go
      - lua
      - npm
      - python
      - rust

      # Visual
      - gpg

      # Applications
      - applications
      - common
      - git
      - gtk
      - latex
      - mpd
      - neovim
      - obsidian
      - playerctl
      - rider
      - rofi
      - ssh
      - tldr
      - utilities
      - vifm
      - wezterm
      - zathura
  tasks:
    # - name: "Print modules"
    #   ansible.builtin.debug:
    #     var: modules
    # - name: "Print data"
    #   ansible.builtin.debug:
    #     var: data
    - name: Run all modules
      ansible.builtin.include_role:
        name: "{{ item }}"
      loop: "{{ modules }}"
