# vi: set ft=yaml.ansible :

- name: Configure Windows WSL
  hosts: localhost
  connection: local
  vars_files:
    - ../vars/windows_wsl.yml
  pre_tasks:
    - name: Merge variables
      ansible.builtin.include_tasks: ../tasks/merge_vars.yml
  # tasks:
  #   - name: Debug variables
  #     ansible.builtin.include_tasks: ../tasks/debug_vars.yml
  roles:
    # Basics
    - system
    - zsh
    - windows_wsl

    # Programming languages
    - lua
    - npm
    - python
    - rust

    # Applications
    - git
    - gpg
    - neovim
    - tldr
    - utilities
    - zoxide
