- name: Install bitwarden
  community.general.npm:
    name: "@bitwarden/cli"
    global: true
    state: present

- name: Install bitwarden packages (apt)
  ansible.builtin.import_tasks: apt.yml
  when:
    - install
    - package_manager == "apt"

- name: Install bitwarden packages (pacman)
  ansible.builtin.import_tasks: pacman.yml
  when:
    - install
    - package_manager == "pacman"

- name: Initialise the path template
  ansible.builtin.template:
    src: "path.zsh.j2"
    dest: "{{ role_path }}/path.zsh"
    mode: u=rw,g=r,o=r

- name: Initialise pwdfzf template
  ansible.builtin.template:
    src: "pwdfzf.j2"
    dest: "{{ role_path }}/bin/_pwdfzf-bin-script"
    mode: u=rwx,g=rx,o=rx
  when:
    - data.system.copy_command is defined
    - data.system.copy_command != ""

- name: Initialise pwdshow template
  ansible.builtin.template:
    src: "pwdshow.j2"
    dest: "{{ role_path }}/bin/_pwdshow-bin-script"
    mode: u=rwx,g=rx,o=rx
