- name: Install bitwarden
  community.general.npm:
    name: "@bitwarden/cli"
    global: true
    state: present

- name: Install bitwarden packages (apt)
  ansible.builtin.import_tasks: apt.yml
  when:
    - install
    - package_manager == "apt"

- name: Install bitwarden packages (pacman)
  ansible.builtin.import_tasks: pacman.yml
  when:
    - install
    - package_manager == "pacman"

- name: Fish configuration
  ansible.builtin.import_tasks: fish.yml
  when:
    - "'fish' in modules"

- name: Zsh configuration
  ansible.builtin.import_tasks: zsh.yml
  when:
    - "'zsh' in modules"
