- name: Install bitwarden
  community.general.npm:
    name: "@bitwarden/cli"
    global: true
    state: present

- name: Install bitwarden packages (apt)
  ansible.builtin.import_tasks: apt.yml
  when:
    - install
    - package_manager == "apt"

- name: Install bitwarden packages (pacman)
  ansible.builtin.import_tasks: pacman.yml
  when:
    - install
    - package_manager == "pacman"

- name: Initialise the path template
  ansible.builtin.template:
    src: "path.zsh.j2"
    dest: "{{ role_path }}/path.zsh"
    mode: u=rw,g=r,o=r

- name: Initialise pwdfzf template
  ansible.builtin.template:
    src: "pwdfzf.j2"
    dest: "{{ role_path }}/bin/_pwdfzf-bin-script"
    mode: u=rwx,g=rx,o=rx

- name: Initialise pwdshow template
  ansible.builtin.template:
    src: "pwdshow.j2"
    dest: "{{ role_path }}/bin/_pwdshow-bin-script"
    mode: u=rwx,g=rx,o=rx

- name: Initialise pwdssh template
  ansible.builtin.template:
    src: "pwdsingle.j2"
    dest: "{{ role_path }}/bin/_pwdssh-bin-script"
    mode: u=rwx,g=rx,o=rx
  vars:
    bw_item: "{{ bw_ssh_item_name }}"
  when: bw_ssh_item_name is defined

- name: Initialise pwdpgp template
  ansible.builtin.template:
    src: "pwdsingle.j2"
    dest: "{{ role_path }}/bin/_pwdpgp-bin-script"
    mode: u=rwx,g=rx,o=rx
  vars:
    bw_item: "{{ bw_pgp_item_name }}"
  when: bw_pgp_item_name is defined
