- name: Install bitwarden
  npm:
    name: "@bitwarden/cli"
    global: true
    state: present

- import_tasks: apt.yml
  when: package_manager == "apt"

- import_tasks: pacman.yml
  when: package_manager == "pacman"

- name: Initialise the path template
  template: 
    src: "path.zsh.j2"
    dest: "{{ role_path }}/path.zsh"

- name: Initialise pwdfzf template
  template:
    src: "pwdfzf.j2"
    dest: "{{ role_path }}/bin/_pwdfzf-bin-script"
    mode: u=rwx,g=rx,o=rx

- name: Initialise pwdshow template
  template:
    src: "pwdshow.j2"
    dest: "{{ role_path }}/bin/_pwdshow-bin-script"
    mode: u=rwx,g=rx,o=rx
