- name: Create awesomeWM config directory
  file: 
    path: "{{ awesome_install_path }}"
    state: directory

- name: Link awesomeWM config
  file:
    src: "{{ role_path }}/rc.4.2.arch-laptop.lua"
    dest: "{{ awesome_install_path }}/rc.lua"
    state: link

- name: Cloning seoul256 theme
  git:
    repo: "https://github.com/Irubataru/seoul256-awesomewm-theme.git"
    dest: "{{ awesome_install_path }}/seoul256-awesomewm-theme"
    update: no


- name: Install lain
  git: 
    repo: "https://github.com/lcpz/lain.git"
    dest: "{{ awesome_install_path }}/lain"
    update: no
