- name: Install build dependencies (apt)
  apt:
    name:
      - cmake
      - lua5.2
      - lua5.3
      - liblua5.2-dev
      - liblua5.3-dev
      - lua-lgi-dev
      - lua-ldoc
      - imagemagick
      - libglib2.0-dev
      - libgdk-pixbuf2.0-dev
      - libcairo2-dev
      - libx11-dev
      - libxcb1-dev
      - libxcb-cursor-dev0
      - libxcb-randr0-dev
      - libxcb-xtest0-dev
      - libxcb-xinerama0-dev
      - libxcb-shape0-dev
      - libxcb-util-dev
      - libxcb-keysyms1-dev
      - libxcb-icccm4-dev
      - libxcb-xfixes0-dev
      - libxcb-xkb-dev
      - libxkbcommon-dev
      - libxkbcommon-x11-dev
      - libstartup-notification0-dev
      - libxdg-basedir-dev
      - libxcb-xrm-dev
    state: present
  become: true
  when: package_manager == "apt"
