- name: Install awesomeWM (aur)
  kewlfft.aur.aur:
    name: awesome-git
    state: present
  become: true
  when: package_manager == "pacman"

- name: Install awesomeWM (apt)
  apt:
    name: awesome
    state: present
  become: true
  when: package_manager == "apt"

- import_tasks: awesome.4.config.yml
  when: awesome_version == 4
