# vi: set ft=yaml.ansible :

- name: Install awesomeWM (aur)
  kewlfft.aur.aur:
    name: awesome-git
    state: present
  become: true
  become_user: aur_builder
  when: package_manager == "pacman"

- name: Install awesomeWM (apt)
  apt:
    name: awesome
    state: present
  become: true
  when: package_manager == "apt"

- name: Instrall awesmeWM dependencies (pacman)
  pacman:
    name: maim
    state: present
  become: true
  when: package_manager == "pacman"

- name: Link awesomeWM config
  file:
    src: "{{ role_path }}/config"
    dest: "{{ home_directory }}/.config/awesome"
    state: link

- name: Install lain
  git: 
    repo: "https://github.com/lcpz/lain.git"
    dest: "{{ role_path }}/config/lain"
    update: no
