# vi: set ft=yaml.ansible :

- name: Install awesomeWM (aur)
  kewlfft.aur.aur:
    name: awesome-git
    state: present
  become: true
  become_user: aur_builder
  when: package_manager == "pacman"

- name: Install awesomeWM (apt)
  apt:
    name: awesome
    state: present
  become: true
  when: package_manager == "apt"

- name: Instrall awesmeWM dependencies (pacman)
  pacman:
    name: maim
    state: present
  become: true
  when: package_manager == "pacman"

- import_tasks: awesome.4.config.yml
  when: awesome_version == 4
