# vi: set ft=yaml.ansible :

- name: Update default vars
  ansible.builtin.set_fact:
    awesome: "{{ awesome | combine(data.software.awesome, recursive=True) }}"
  when: data.software.awesome is defined

- name: Install awesomeWM (aur)
  kewlfft.aur.aur:
    name: awesome-git
    state: present
  become: true
  become_user: aur_builder
  when:
    - install
    - package_manager == "pacman"

- name: Install awesomeWM (apt)
  ansible.builtin.apt:
    name: awesome
    state: present
  become: true
  when:
    - install
    - package_manager == "apt"

- name: Instrall awesmeWM dependencies (pacman)
  community.general.pacman:
    name:
      - brightnessctl
      - maim
    state: present
  become: true
  when:
    - install
    - package_manager == "pacman"

- name: Link awesomeWM config
  ansible.builtin.file:
    src: "{{ role_path }}/config"
    dest: "{{ home_directory }}/.config/awesome"
    state: link

- name: Install lain
  ansible.builtin.git:
    repo: "https://github.com/lcpz/lain.git"
    dest: "{{ role_path }}/config/lain"
    update: false
