# vi: set ft=yaml.ansible :

- name: Install Ubuntu software properties
  ansible.builtin.apt:
    name: software-properties-common
    state: present
  become: true

- name: Add neovim development ppa
  ansible.builtin.apt_repository:
    repo: ppa:neovim-ppa/unstable
  become: true

- name: Install neovim
  ansible.builtin.apt:
    name:
      - python3-dev
      - python3-pip
      - neovim
    state: present
  become: true
