# vi: set ft=yaml.ansible :

- name: Update default vars
  ansible.builtin.set_fact:
    neovim: "{{ neovim | combine(data.software.neovim, recursive=True) }}"
  when: data.software.neovim is defined

- name: Install neovim using pacman
  ansible.builtin.import_tasks: pacman.yml
  when:
    - install
    - package_manager == "pacman"

- name: Install neovim using apt
  ansible.builtin.import_tasks: apt.yml
  when:
    - install
    - package_manager == "apt"

- name: Fish configuration
  ansible.builtin.import_tasks: fish.yml
  when:
    - "'fish' in modules"

- name: Create vim temp storage directory
  ansible.builtin.file:
    path: "{{ home_directory }}/.tmp"
    state: directory
    mode: u=rwx,g=rx,o=rx

- name: Create neovim config directory
  ansible.builtin.file:
    path: "{{ home_directory }}/.config"
    state: directory
    mode: u=rwx,g=rx,o=rx

- name: Link neovim config
  ansible.builtin.file:
    src: "{{ role_path }}/config"
    dest: "{{ home_directory }}/.config/nvim"
    state: link
