# vi: set ft=yaml.ansible :

- import_tasks: pacman.yml
  when:
    - install
    - package_manager == "pacman"

- import_tasks: apt.yml
  when:
    - install
    - package_manager == "apt"

- name: Create vim temp storage directory
  file: 
    path: "{{ home_directory }}/.tmp"
    state: directory

- name: Create neovim config directory
  file: 
    path: "{{ home_directory }}/.config"
    state: directory

- name: Link neovim config
  file:
    src: "{{ role_path }}/config"
    dest: "{{ home_directory }}/.config/nvim"
    state: link

