- import_tasks: pacman.yml
  when: package_manager == "pacman"

- import_tasks: apt.yml
  when: package_manager == "apt"

- name: Create vim temp storage directory
  file: 
    path: "{{ home_directory }}/.tmp"
    state: directory

- name: Create neovim config directory
  file: 
    path: "{{ home_directory }}/.config"
    state: directory

- name: Link neovim config
  file:
    src: "{{ role_path }}/config"
    dest: "{{ home_directory }}/.config/nvim"
    state: link

- name: Install neovim python dependencies
  pip:
    name:
      - pynvim
      - pyright
    extra_args: --user
    state: latest
  ignore_errors: true

- name: Install neovim ruby dependencies
  gem:
    name: neovim
    user_install: true
    state: latest
  ignore_errors: true

- name: Install typescript (npm)
  npm:
    name: typescript
    global: true
    state: present

- name: Install typescript language server (npm)
  npm:
    name: typescript-language-server
    global: true
    state: present

- name: Install json language server (npm)
  npm:
    name: vscode-langservers-extracted
    global: true
    state: present

- name: Install docker file language server (npm)
  npm:
    name: dockerfile-language-server-nodejs
    global: true
    state: latest
  ignore_errors: true

- name: Install eslint_d (npm)
  npm:
    name: eslint_d
    global: true
    state: latest
  ignore_errors: true

- name: Install prettierd (npm)
  npm:
    name: "@fsouza/prettierd"
    global: true
    state: latest
  ignore_errors: true
