# vi: set ft=yaml.ansible :

- name: Install neovim
  pacman:
    name: neovim
    state: present
  become: true
  when: not neovim_git

- name: Install neovim-git
  kewlfft.aur.aur:
    name: neovim-git
    state: present
  become: true
  become_user: aur_builder
  when: neovim_git

- name: Install neovim utilities (AUR)
  kewlfft.aur.aur:
    name:
      - glow
    state: present
  become: true
  become_user: aur_builder

- name: Install neovim python dependencies (pacman)
  community.general.pacman:
    name:
      - python-pynvim
      - pyright
      - autopep8
    state: latest
  become: true
  when: install
