- name: Install neovim
  kewlfft.aur.aur:
    name: neovim-git
    state: present
  become: true
  become_user: aur_builder

- name: Install neovim language servers (AUR)
  kewlfft.aur.aur:
    name:
      - omnisharp-roslyn-bin
    state: present
  become: true
  become_user: aur_builder

- name: Install neovim language servers (AUR)
  npm:
    name: dockerfile-language-server-nodejs
    global: true
    state: present
