# vi: set ft=yaml.ansible :

- name: Check if Fira Code has been downloaded
  ansible.builtin.stat:
    path: "{{ role_path }}/FiraCode.zip"
  register: fira_code_file

- name: Download Fira Code nerd font
  ansible.builtin.get_url:
    url: "{{ fonts.fira_path }}"
    dest: "{{ role_path }}"
  when: fira_code_file.stat.exists == false

- name: Creating Fira Code font unpack dir
  ansible.builtin.file:
    path: "{{ role_path }}/FiraCode"
    state: directory
    mode: u=rwx,g=rx,o=rx


- name: Unzipping Fira Code font files
  ansible.builtin.unarchive:
    src: "{{ role_path }}/FiraCode.zip"
    dest: "{{ role_path }}/FiraCode"
    copy: false
  when: fira_code_file.stat.exists == false

- name: Creating global Fira Code font directory
  ansible.builtin.file:
    path: /usr/share/fonts/truetype/FiraCode
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
    state: directory
  become: true
  when: fonts.install_global and not fira_code_file.stat.exists

- name: Installing Fira Code font globally
  ansible.builtin.copy:
    src: "{{ font_file }}"
    dest: /usr/share/fonts/truetype/FiraCode
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  with_fileglob: "{{ role_path }}/FiraCode/*"
  loop_control:
    loop_var: font_file
  become: true
  when: fonts.install_global and not fira_code_file.stat.exists
  register: fira_code_install

- name: Update font cache
  ansible.builtin.shell: fc-cache -f -v
  when: fira_code_install.changed
