- name: Check if Fira Code has been downloaded
  stat:
    path: "{{ role_path }}/FiraCode.zip"
  register: fira_code_file

- name: Download Fira Code nerd font
  get_url:
    url: "{{ fonts_fira_path }}"
    dest: "{{ role_path }}"
  when: fira_code_file.stat.exists == false

- name: Creating Fira Code font unpack dir
  file: 
    path: "{{ role_path}}/FiraCode"
    state: directory

- name: Unzipping Fira Code font files
  unarchive:
    src: "{{ role_path }}/FiraCode.zip"
    dest: "{{ role_path}}/FiraCode"
    copy: no
  when: fira_code_file.stat.exists == false

- name: Creating global Fira Code font directory
  file:
    path: /usr/share/fonts/truetype/FiraCode
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
    state: directory
  become: true
  when: fonts_global_install == true && fira_code_file.stat.exists == false

- name: Installing Fira Code font globally
  copy:
    src: "{{ font_file }}"
    dest: /usr/share/fonts/truetype/FiraCode
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  with_fileglob: "{{ role_path }}/FiraCode/*"
  loop_control:
    loop_var: font_file
  become: true
  when: fonts_global_install == true && fira_code_file.stat.exists == false
  register: fira_code_install

- name: Update font cache
  shell: fc-cache -f -v
  when: fira_code_install.changed
