- name: Check if Hack has been downloaded
  stat:
    path: "{{ role_path }}/Hack.zip"
  register: hack_file

- name: Download Hack nerd font
  get_url:
    url: "{{ fonts_hack_path }}"
    dest: "{{ role_path }}"
  when: hack_file.stat.exists == false

- name: Creating Hack font unpack dir
  file: 
    path: "{{ role_path}}/Hack"
    state: directory

- name: Unzipping Hack font files
  unarchive:
    src: "{{ role_path }}/Hack.zip"
    dest: "{{ role_path}}/Hack"
    copy: no

- name: Creating global Hack font directory
  file:
    path: /usr/share/fonts/truetype/Hack
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
    state: directory
  become: true
  when: fonts_global_install == true

- name: Installing Hack font globally
  copy:
    src: "{{ font_file }}"
    dest: /usr/share/fonts/truetype/Hack
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  with_fileglob: "{{ role_path }}/Hack/*"
  loop_control:
    loop_var: font_file
  become: true
  when: fonts_global_install == true
  register: hack_install

- name: Update font cache
  shell: fc-cache -f -v
  when: hack_install.changed
