- import_tasks: pacman.yml
  when: package_manager == "pacman"

- import_tasks: hack.yml
  when: package_manager != "pacman"

- import_tasks: fira_code.yml
  when: package_manager != "pacman"

- import_tasks: private.yml
