# vi: set ft=yaml.ansible :

- name: Update default vars
  ansible.builtin.set_fact:
    fonts: "{{ fonts | combine(data.software.fonts, recursive=True) }}"
  when: data.software.fonts is defined

- name: "Install fonts with pacman"
  ansible.builtin.import_tasks: pacman.yml
  when:
    - install
    - package_manager == "pacman"

- name: "Install hack font without pacman"
  ansible.builtin.import_tasks: hack.yml
  when:
    - install
    - package_manager != "pacman"

- name: "Install fira code font without pacman"
  ansible.builtin.import_tasks: fira_code.yml
  when:
    - install
    - package_manager != "pacman"

# - name: Create fontconfig directory
#   file:
#     path: "{{ home_directory }}/.config/fontconfig"
#     state: directory
#
# - name: Link fontconfig
#   file:
#     src: "{ role_path}/fonts.conf"
#     dest: "{{ home_directory }}/.config/fontconfig/fonts.conf"
#     state: link

- name: "Install private fonts"
  ansible.builtin.import_tasks: private.yml
  when: install
